// Checks supabase/car-catalog.csv (the car list owners pick from) and, given a path, writes it as a seed migration.
//
//   node --experimental-strip-types scripts/car-catalog.ts                      check only
//   node --experimental-strip-types scripts/car-catalog.ts supabase/migrations/<stamp>_car_catalog_seed.sql
//
// The CSV is the source of truth: edit it, run this, push the new migration. Re-running is safe (rows upsert by name).
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const TYPES = ['sedan', 'hatchback', 'suv', 'coupe', 'sports', 'convertible', 'pickup', 'van'];
const [header, ...lines] = readFileSync(join(import.meta.dirname, '../supabase/car-catalog.csv'), 'utf8').trim().split(/\r?\n/); // Excel saves CRLF
assert.equal(header, 'brand_en,brand_ar,model_en,model_ar,car_type,brand_rank');

const makes = new Map<string, { ar: string; rank: number }>();
const seen = new Set<string>();
const models = lines.map((line, i) => {
  const cells = line.split(',').map((c) => c.trim());
  const [brand, brandAr, model, modelAr, type, rank] = cells;
  const where = `line ${i + 2}: ${line}`;
  assert.equal(cells.length, 6, where); // names never contain a comma
  assert.ok(brand && brandAr && model && modelAr, `empty name, ${where}`);
  assert.ok(TYPES.includes(type), `unknown car type, ${where}`);
  assert.ok(Number.isInteger(Number(rank)) && Number(rank) > 0, `bad rank, ${where}`);
  const key = `${brand}|${model}`.toLowerCase();
  assert.ok(!seen.has(key), `duplicate, ${where}`);
  seen.add(key);
  const known = makes.get(brand);
  if (known) assert.deepEqual(known, { ar: brandAr, rank: Number(rank) }, `brand spelled or ranked two ways, ${where}`);
  else makes.set(brand, { ar: brandAr, rank: Number(rank) });
  return { brand, model, modelAr, type };
});
console.log(`${models.length} models, ${makes.size} brands: ok`);

const out = process.argv[2];
if (out) {
  const q = (s: string) => `'${s.replaceAll("'", "''")}'`;
  writeFileSync(out, `-- Generated by scripts/car-catalog.ts from supabase/car-catalog.csv. Do not edit by hand.
insert into public.car_makes (name_en, name_ar, sort) values
${[...makes].map(([en, m]) => `  (${q(en)}, ${q(m.ar)}, ${m.rank})`).join(',\n')}
on conflict (name_en) do update set name_ar = excluded.name_ar, sort = excluded.sort;

insert into public.car_models (make_id, name_en, name_ar, body_type)
select m.id, v.name_en, v.name_ar, v.body_type
from (values
${models.map((m) => `  (${q(m.brand)}, ${q(m.model)}, ${q(m.modelAr)}, ${q(m.type)})`).join(',\n')}
) as v(make, name_en, name_ar, body_type)
join public.car_makes m on m.name_en = v.make
on conflict (make_id, name_en) do update set name_ar = excluded.name_ar, body_type = excluded.body_type;
`);
  console.log(`wrote ${out}`);
}
