// Checks supabase/record-catalog.csv (categories, subcategories and services of a record) and, given a path,
// writes it as a seed migration.
//
//   node --experimental-strip-types scripts/record-catalog.ts                      check only
//   node --experimental-strip-types scripts/record-catalog.ts supabase/migrations/<stamp>_record_catalog_seed.sql
//
// The CSV is the source of truth. Existing services are matched by their English name, so logs keep their links.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FIELDS = ['brand', 'grade', 'quantity', 'size', 'count', 'warranty_months', 'liters', 'odometer'];
const CODES = ['fuel', 'wash', 'parking', 'tolls', 'insurance', 'registration', 'parts', 'other'];
const [header, ...lines] = readFileSync(join(import.meta.dirname, '../supabase/record-catalog.csv'), 'utf8').trim().split(/\r?\n/); // Excel saves CRLF
assert.equal(header, 'category_en,category_ar,subcategory_en,subcategory_ar,service_en,service_ar,kind,reminder,default_km,default_months,fields,icon,expense_code');

const cats = new Map<string, string>(); // en → ar, in sheet order
const subs = new Map<string, { cat: string; en: string; ar: string; icon: string; code: string }>();
const services: { sub: string; en: string; ar: string; reminder: boolean; km: string; months: string; fields: string[]; icon: string }[] = [];
const seen = new Set<string>();
lines.forEach((line, i) => {
  const c = line.split(',').map((x) => x.trim());
  const where = `line ${i + 2}: ${line}`;
  assert.equal(c.length, 13, where); // names never contain a comma
  const [cat, catAr, sub, subAr, en, ar, kind, reminder, km, months, fields, icon, code] = c;
  assert.ok(cat && catAr && sub && subAr && icon, `empty name or icon, ${where}`);
  assert.ok(['maintenance', 'cost'].includes(kind) && ['yes', 'no'].includes(reminder), where);
  const list = fields ? fields.split(' ') : [];
  assert.ok(list.every((f) => FIELDS.includes(f)), `unknown field, ${where}`);
  assert.ok(/^\d*$/.test(km) && /^\d*$/.test(months), where);
  assert.ok(!cats.has(cat) || cats.get(cat) === catAr, `category spelled two ways, ${where}`);
  cats.set(cat, catAr);
  const key = `${cat}|${sub}`;
  if (kind === 'cost') {
    assert.ok(!en && !ar && reminder === 'no' && CODES.includes(code) && !subs.has(key), where);
    subs.set(key, { cat, en: sub, ar: subAr, icon, code });
    return;
  }
  assert.ok(en && ar && !code, where);
  assert.ok(reminder === 'no' ? !km && !months : !!km, `a reminder needs a default distance, ${where}`);
  assert.ok(!seen.has(en.toLowerCase()), `duplicate service, ${where}`);
  seen.add(en.toLowerCase());
  if (!subs.has(key)) subs.set(key, { cat, en: sub, ar: subAr, icon, code: '' });
  services.push({ sub: key, en, ar, reminder: reminder === 'yes', km, months, fields: list, icon });
});
console.log(`${cats.size} categories, ${subs.size} subcategories, ${services.length} services: ok`);

const out = process.argv[2];
if (out) {
  const q = (s: string) => `'${s.replaceAll("'", "''")}'`;
  const n = (s: string) => s || 'null';
  writeFileSync(out, `-- Generated by scripts/record-catalog.ts from supabase/record-catalog.csv. Do not edit by hand.
insert into public.record_categories (name_en, name_ar, sort) values
${[...cats].map(([en, ar], i) => `  (${q(en)}, ${q(ar)}, ${i + 1})`).join(',\n')};

insert into public.record_categories (parent_id, name_en, name_ar, icon, sort, expense_code)
select p.id, v.name_en, v.name_ar, v.icon, v.sort, v.code
from (values
${[...subs.values()].map((s, i) => `  (${q(s.cat)}, ${q(s.en)}, ${q(s.ar)}, ${q(s.icon)}, ${i + 1}, ${s.code ? q(s.code) : 'null'})`).join(',\n')}
) as v(cat, name_en, name_ar, icon, sort, code)
join public.record_categories p on p.name_en = v.cat and p.parent_id is null;

-- Services: the ones that already exist keep their id (old logs point at them); the rest are new.
with v(cat, sub, name_en, name_ar, has_reminder, km, months, fields, icon, sort) as (values
${services.map((s, i) => { const [cat, sub] = s.sub.split('|'); return `  (${q(cat)}, ${q(sub)}, ${q(s.en)}, ${q(s.ar)}, ${s.reminder}, ${n(s.km)}::int, ${n(s.months)}::int, '{${s.fields.join(',')}}'::text[], ${q(s.icon)}, ${i + 1})`; }).join(',\n')}
), placed as (
  select v.*, c.id as category_id
  from v join public.record_categories p on p.name_en = v.cat and p.parent_id is null
         join public.record_categories c on c.name_en = v.sub and c.parent_id = p.id
), updated as (
  update public.service_types s
  set name_ar = placed.name_ar, category_id = placed.category_id, has_reminder = placed.has_reminder,
      default_interval_km = placed.km, default_interval_months = placed.months, fields = placed.fields, icon = placed.icon, sort = placed.sort
  from placed where s.name_en = placed.name_en
  returning s.name_en
)
insert into public.service_types (name_en, name_ar, category_id, has_reminder, default_interval_km, default_interval_months, fields, icon, sort)
select name_en, name_ar, category_id, has_reminder, km, months, fields, icon, sort
from placed where name_en not in (select name_en from updated);

-- A service left out of the sheet is retired (Car Wash became a running cost): it no longer reminds.
update public.service_types set has_reminder = false where category_id is null;
`);
  console.log(`wrote ${out}`);
}
