-- Generated by scripts/record-catalog.ts from supabase/record-catalog.csv. Do not edit by hand.
insert into public.record_categories (name_en, name_ar, sort) values
  ('Engine & oil', 'المحرك والزيت', 1),
  ('Filters', 'الفلاتر', 2),
  ('Brakes', 'الفرامل', 3),
  ('Tyres & wheels', 'الإطارات والعجل', 4),
  ('Battery & electrics', 'البطارية والكهرباء', 5),
  ('Cooling & AC', 'التبريد والتكييف', 6),
  ('Transmission', 'ناقل الحركة', 7),
  ('Suspension & steering', 'العفشة والدركسيون', 8),
  ('Body & glass', 'الهيكل والزجاج', 9),
  ('Inspection & repairs', 'الفحص والإصلاحات', 10),
  ('Fuel', 'الوقود', 11),
  ('Cleaning', 'النظافة', 12),
  ('Parking & tolls', 'الركن والكارتة', 13),
  ('Papers & insurance', 'الأوراق والتأمين', 14),
  ('Parts bought', 'قطع غيار', 15),
  ('Other', 'أخرى', 16);

insert into public.record_categories (parent_id, name_en, name_ar, icon, sort, expense_code)
select p.id, v.name_en, v.name_ar, v.icon, v.sort, v.code
from (values
  ('Engine & oil', 'Engine oil', 'زيت المحرك', 'Droplets', 1, null),
  ('Engine & oil', 'Engine', 'المحرك', 'Zap', 2, null),
  ('Filters', 'Air', 'الهواء', 'Wind', 3, null),
  ('Filters', 'Fuel', 'الوقود', 'Filter', 4, null),
  ('Brakes', 'Pads & discs', 'التيل والطنابير', 'Disc', 5, null),
  ('Brakes', 'Brake fluid', 'زيت الفرامل', 'Droplets', 6, null),
  ('Brakes', 'Inspection', 'الفحص', 'CircleAlert', 7, null),
  ('Tyres & wheels', 'Tyres', 'الإطارات', 'Circle', 8, null),
  ('Tyres & wheels', 'Wheels', 'العجل', 'RefreshCcw', 9, null),
  ('Battery & electrics', 'Battery', 'البطارية', 'BatteryCharging', 10, null),
  ('Battery & electrics', 'Lights', 'الإضاءة', 'Zap', 11, null),
  ('Cooling & AC', 'Cooling', 'التبريد', 'Thermometer', 12, null),
  ('Cooling & AC', 'AC', 'التكييف', 'Snowflake', 13, null),
  ('Transmission', 'Gearbox', 'الفتيس', 'Settings', 14, null),
  ('Suspension & steering', 'Suspension', 'العفشة', 'Wrench', 15, null),
  ('Body & glass', 'Wipers', 'المساحات', 'CloudRain', 16, null),
  ('Body & glass', 'Body', 'الهيكل', 'Wrench', 17, null),
  ('Body & glass', 'Glass', 'الزجاج', 'Wrench', 18, null),
  ('Inspection & repairs', 'Inspection', 'الفحص', 'ClipboardCheck', 19, null),
  ('Inspection & repairs', 'Repairs', 'الإصلاحات', 'Wrench', 20, null),
  ('Fuel', 'Fuel', 'الوقود', 'Fuel', 21, 'fuel'),
  ('Cleaning', 'Car wash', 'غسيل السيارة', 'Sparkles', 22, 'wash'),
  ('Parking & tolls', 'Parking', 'الركن', 'ParkingCircle', 23, 'parking'),
  ('Parking & tolls', 'Tolls', 'الكارتة والرسوم', 'Ticket', 24, 'tolls'),
  ('Papers & insurance', 'Insurance', 'التأمين', 'ShieldCheck', 25, 'insurance'),
  ('Papers & insurance', 'Licence renewal', 'تجديد الرخصة', 'FileText', 26, 'registration'),
  ('Parts bought', 'Spare parts', 'قطع غيار', 'Package', 27, 'parts'),
  ('Other', 'Other', 'أخرى', 'Receipt', 28, 'other')
) as v(cat, name_en, name_ar, icon, sort, code)
join public.record_categories p on p.name_en = v.cat and p.parent_id is null;

-- Services: the ones that already exist keep their id (old logs point at them); the rest are new.
with v(cat, sub, name_en, name_ar, has_reminder, km, months, fields, icon, sort) as (values
  ('Engine & oil', 'Engine oil', 'Oil Change', 'تغيير الزيت', true, 5000::int, 6::int, '{brand,grade,quantity}'::text[], 'Droplets', 1),
  ('Engine & oil', 'Engine oil', 'Oil Filter', 'فلتر الزيت', true, 5000::int, 6::int, '{brand}'::text[], 'Filter', 2),
  ('Engine & oil', 'Engine', 'Spark Plug Replacement', 'تغيير شمعات الاحتراق', true, 30000::int, null::int, '{brand,count}'::text[], 'Zap', 3),
  ('Engine & oil', 'Engine', 'Timing Belt', 'تغيير سير التوقيت', true, 100000::int, null::int, '{brand}'::text[], 'Timer', 4),
  ('Engine & oil', 'Engine', 'Drive Belt', 'تغيير سير الدينامو', true, 60000::int, null::int, '{brand}'::text[], 'Timer', 5),
  ('Filters', 'Air', 'Air Filter', 'فلتر الهواء', true, 15000::int, 12::int, '{brand}'::text[], 'Wind', 6),
  ('Filters', 'Air', 'Cabin Filter', 'فلتر التكييف', true, 15000::int, 12::int, '{brand}'::text[], 'Wind', 7),
  ('Filters', 'Fuel', 'Fuel Filter', 'فلتر البنزين', true, 40000::int, null::int, '{brand}'::text[], 'Filter', 8),
  ('Brakes', 'Pads & discs', 'Brake Pad Replacement', 'تغيير تيل الفرامل', true, 40000::int, null::int, '{brand}'::text[], 'Disc', 9),
  ('Brakes', 'Pads & discs', 'Brake Disc Replacement', 'تغيير طنابير الفرامل', true, 80000::int, null::int, '{brand}'::text[], 'Disc', 10),
  ('Brakes', 'Brake fluid', 'Brake Fluid Change', 'تغيير زيت الفرامل', true, 40000::int, 24::int, '{brand}'::text[], 'Droplets', 11),
  ('Brakes', 'Inspection', 'Brake Inspection', 'فحص الفرامل', true, 20000::int, 12::int, '{}'::text[], 'CircleAlert', 12),
  ('Tyres & wheels', 'Tyres', 'Tire Replacement', 'تغيير الإطارات', true, 50000::int, null::int, '{brand,size,count}'::text[], 'Circle', 13),
  ('Tyres & wheels', 'Tyres', 'Tire Rotation', 'تبديل الإطارات', true, 10000::int, 6::int, '{}'::text[], 'RefreshCcw', 14),
  ('Tyres & wheels', 'Wheels', 'Wheel Alignment & Balancing', 'ضبط زوايا وترصيص', true, 10000::int, 6::int, '{}'::text[], 'RefreshCcw', 15),
  ('Battery & electrics', 'Battery', 'Battery Replacement', 'تغيير البطارية', true, 60000::int, 36::int, '{brand,warranty_months}'::text[], 'BatteryCharging', 16),
  ('Battery & electrics', 'Battery', 'Battery Check', 'فحص البطارية', true, 10000::int, 6::int, '{}'::text[], 'BatteryFull', 17),
  ('Battery & electrics', 'Lights', 'Bulb Replacement', 'تغيير لمبات', false, null::int, null::int, '{brand}'::text[], 'Zap', 18),
  ('Cooling & AC', 'Cooling', 'Coolant Check', 'فحص سائل التبريد', true, 30000::int, 12::int, '{}'::text[], 'Thermometer', 19),
  ('Cooling & AC', 'Cooling', 'Coolant Change', 'تغيير مياه الردياتير', true, 40000::int, 24::int, '{brand}'::text[], 'Thermometer', 20),
  ('Cooling & AC', 'AC', 'AC Service', 'فحص التكييف', true, 20000::int, 12::int, '{}'::text[], 'Snowflake', 21),
  ('Cooling & AC', 'AC', 'AC Gas Refill', 'شحن فريون التكييف', false, null::int, null::int, '{}'::text[], 'Snowflake', 22),
  ('Transmission', 'Gearbox', 'Transmission Check', 'فحص ناقل الحركة', true, 60000::int, 24::int, '{}'::text[], 'Settings', 23),
  ('Transmission', 'Gearbox', 'Transmission Oil Change', 'تغيير زيت الفتيس', true, 60000::int, null::int, '{brand,grade}'::text[], 'Settings', 24),
  ('Suspension & steering', 'Suspension', 'Shock Absorbers', 'تغيير المساعدين', true, 80000::int, null::int, '{brand,count}'::text[], 'Wrench', 25),
  ('Suspension & steering', 'Suspension', 'Suspension Repair', 'إصلاح العفشة', false, null::int, null::int, '{}'::text[], 'Wrench', 26),
  ('Body & glass', 'Wipers', 'Wiper Replacement', 'تغيير مساحات الزجاج', true, 20000::int, 12::int, '{brand}'::text[], 'CloudRain', 27),
  ('Body & glass', 'Body', 'Body & Paint Repair', 'سمكرة ودهان', false, null::int, null::int, '{}'::text[], 'Wrench', 28),
  ('Body & glass', 'Glass', 'Glass Repair', 'إصلاح أو تغيير الزجاج', false, null::int, null::int, '{}'::text[], 'Wrench', 29),
  ('Inspection & repairs', 'Inspection', 'Full Inspection', 'فحص دوري شامل', true, 20000::int, 12::int, '{}'::text[], 'ClipboardCheck', 30),
  ('Inspection & repairs', 'Repairs', 'General Repair', 'إصلاح عام', false, null::int, null::int, '{}'::text[], 'Wrench', 31)
), placed as (
  select v.*, c.id as category_id
  from v join public.record_categories p on p.name_en = v.cat and p.parent_id is null
         join public.record_categories c on c.name_en = v.sub and c.parent_id = p.id
), updated as (
  update public.service_types s
  set name_ar = placed.name_ar, category_id = placed.category_id, has_reminder = placed.has_reminder,
      default_interval_km = placed.km, default_interval_months = placed.months, fields = placed.fields, icon = placed.icon, sort = placed.sort
  from placed where s.name_en = placed.name_en
  returning s.name_en
)
insert into public.service_types (name_en, name_ar, category_id, has_reminder, default_interval_km, default_interval_months, fields, icon, sort)
select name_en, name_ar, category_id, has_reminder, km, months, fields, icon, sort
from placed where name_en not in (select name_en from updated);

-- A service left out of the sheet is retired (Car Wash became a running cost): it no longer reminds.
update public.service_types set has_reminder = false where category_id is null;
